# Generated by Django 5.1.4 on 2025-01-01 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_alter_tag_options_tag_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-count']},
        ),
    ]
